page_title                                : "Nafilah"                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1510691403                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

page_url                                  : https://nafilah.app
appstore_link                             : https://apps.apple.com/app/id1510691403   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
discord_link                              : https://discord.gg/snsKVNXhhs

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Nafilah                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Shia app for daily duas, a'mal, and ziyarat.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mahdi Qazwini                                
your_link                                 : https://mqazwini.com                     
your_city                                 : Canton                                
email_address                             : mmqazwini@yahoo.com
facebook_username                         :                                           
instagram_username                        : mmqazwini
twitter_username                          : 
github_username                           : qazwini
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : English Interface
    description                           : Designed for English speakers with a fully English interace.
    fontawesome_icon_name                 : globe-americas
    
  - title                                 : English Translations & Transliterations
    description                           : English translations & transliterations for duas and a'mal. Additional translations are being added regularly.
    fontawesome_icon_name                 : language

  - title                                 : Arabic & Persion
    description                           : Full support for Arabic and Persian as well.
    fontawesome_icon_name                 : globe-asia

  - title                                 : Audio
    description                           : Download (permanently or temporarily) and listen to audio files for duas (ziyarat and a'mal coming soon).
    fontawesome_icon_name                 : play

  - title                                 : Prayer Times
    description                           : Turn on notifications to be alerted when its time to pray! Or add a prayer times widget on your home screen.
    fontawesome_icon_name                 : clock
  
  - title                                 : Favorites
    description                           : Add any text to your favorties for quick access. Or add a favorites widget to your home screen for faster access.
    fontawesome_icon_name                 : heart

  - title                                 : Search
    description                           : Seamlessly search through the text database by entering the text's title or a word/phrase inside it. English and Arabic! 
    fontawesome_icon_name                 : search

  - title                                 : Customization
    description                           : Custom app icon, custom theme color, custom font and size...
    fontawesome_icon_name                 : eye-dropper

  - title                                 : Dark Mode
    description                           : For the cultured.
    fontawesome_icon_name                 : adjust

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
theme_color                               : "#6066F1"

topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

body_background_color                     : "#ffffff"

link_color                                : "#6066F1" #"#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6066F1" #"#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_bg_color                           : "#f9f9f9"











####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
